# Generated by Django 3.2.16 on 2022-11-22 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='color',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
